import React, { useState } from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Image, VStack, StackDivider, Tooltip, Text, Heading, Flex, Box, Button, Input, InputGroup, InputLeftElement, Spacer, Grid, GridItem, useToast, useDisclosure, ColorModeScript, useColorMode } from '@chakra-ui/react'
import { Drawer, DrawerBody, DrawerFooter, DrawerHeader, DrawerOverlay, DrawerContent, DrawerCloseButton } from '@chakra-ui/react'
import { MoonIcon, SunIcon, SearchIcon, EmailIcon, LockIcon, InfoIcon } from '@chakra-ui/icons'
import { useAuth0 } from '@auth0/auth0-react'

export default function Home() {
  const toast = useToast()
  const { isOpen, onOpen, onClose } = useDisclosure()
  const { colorMode, toggleColorMode } = useColorMode()
  const { loginWithPopup, logout, user, isAuthenticated } = useAuth0()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Flex minWidth='40%' alignItems='center' justifyContent='space-between'>
          <Box p='2'>
            <Heading size='md'>Stripe App</Heading>
          </Box>
          <Flex justifyContent='space-between' align='center'>
            {isAuthenticated ? <Text mr={5}>Hello, {user.nickname}</Text> : null}
            {isAuthenticated ? <Button mr={5} borderRadius='md' onClick={() => logout()}>Log Out</Button> : <Button mr={5} colorScheme='pink' borderRadius='md' onClick={() => loginWithPopup()}>Log In</Button>}
            {colorMode === 'light' ? <MoonIcon boxSize={5} color='black' onClick={toggleColorMode}/> : <SunIcon boxSize={5} color='white' onClick={toggleColorMode}/>}
          </Flex>
        </Flex>
        <Flex h='90vh' direction='column' justify='center' align='center'>
          <Heading size='2xl'>Payments Made Easy. Just For You</Heading>
          <Image src='/images/wallet.png' boxSize={500}/>
          <Button onClick={onOpen}>See What We Offer</Button>
        </Flex>
        <Drawer placement='left' isOpen={isOpen} onClose={onClose}>
          <DrawerOverlay />
          <DrawerContent>
            <DrawerCloseButton />
            <DrawerHeader borderBottomWidth='1px'>Explore Stripe App</DrawerHeader>
            <DrawerBody>
              <Flex direction='column' align='center'>
                <Button w='100%' onClick={() => window.location.href='/payments'}>Make A Payment</Button>
              </Flex>
            </DrawerBody>
          </DrawerContent>
        </Drawer>
      </main>
    </>
  )
}
