import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Image, VStack, StackDivider, Tooltip, Text, Heading, Flex, Box, Button, Input, InputGroup, InputLeftElement, Spacer, Grid, GridItem, useToast, useDisclosure, ColorModeScript, useColorMode } from '@chakra-ui/react'
import { MoonIcon, SunIcon, SearchIcon, EmailIcon, LockIcon, InfoIcon } from '@chakra-ui/icons'

export default function PaymentComplete() {
    const { colorMode, toggleColorMode } = useColorMode()
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Flex minWidth='40%' alignItems='center' justifyContent='space-between'>
                    <Box p='2'>
                        <Heading size='md' onClick={() => window.location.href='/'}>Stripe App</Heading>
                    </Box>
                    <Flex justifyContent='space-between' align='center'>
                        <Button marginRight={5} colorScheme='purple' borderRadius='md' onClick={() => toast({ title: 'Account created.', description: "We've created your account for you.", status: 'success', duartion: 5000, isClosable: true, position: 'top'})}>Sign Up</Button>
                        <Button mr={5} colorScheme='pink' borderRadius='md' onClick={() => toast({title: 'Error.', description: "We can't sign you in right now. Try again later", status: 'error', duration: 5000, isClosable: true, position: 'top'})}>Log In</Button>
                        {colorMode === 'light' ? <MoonIcon boxSize={5} color='black' onClick={toggleColorMode}/> : <SunIcon boxSize={5} color='white' onClick={toggleColorMode}/>}
                    </Flex>
                </Flex>
                <Flex h='80vh' direction='column' justify='center' align='center'>
                    <Heading size='2xl'>Thank you for your purchase</Heading>
                    <Text mt={10} fontSize='xl'>No actual payments were processed</Text>
                </Flex>
            </main>
        </>
    )
}